Repository opendistro-for-elasticsearch/sql, pull requests merged in 2021-03, with the labels that each got.

#1066 Support double value in string format for GeoPoint
  elasticsearch/src/main/java/com/amazon/opendistroforelasticsearch/sql/elasticsearch/data/utils/ElasticsearchJsonContent.java
  elasticsearch/src/test/java/com/amazon/opendistroforelasticsearch/sql/elasticsearch/data/value/ElasticsearchExprValueFactoryTest.java
Labels: enhancement

#1054 Upgrade es-py to add Python3.9 support for sql-cli
  sql-cli/setup.py
Labels: dependencies

#1077 Enable prepared statement support in new engine
  integ-test/src/test/java/com/amazon/opendistroforelasticsearch/sql/sql/PreparedStatementIT.java
  sql/src/main/java/com/amazon/opendistroforelasticsearch/sql/sql/domain/SQLQueryRequest.java
  sql/src/test/java/com/amazon/opendistroforelasticsearch/sql/sql/domain/SQLQueryRequestTest.java
Labels: SQL, enhancement
